import type { Dict } from "../i18n";

export const en: Dict = {
  meta: {
    title: "DrunkCtrl — command center for your FB account farm",
    description:
      "Self-hosted panel to manage hundreds of Facebook ad accounts: check status in seconds, accept policy, bind cards, transfer access, launch ads and pull stats — with a built-in antidetect browser.",
  },
  nav: { why: "why", features: "features", pricing: "pricing", faq: "faq", access: "Access" },
  hero: {
    eyebrow: "FB account management · DrunkFB ecosystem",
    h1a: "Hundreds of FB accounts at hand.",
    h1b: "No limits, no cloud.",
    sub: "DrunkCtrl checks, prepares and launches ads across your accounts — in bulk, one click. And the built-in antidetect browser opens any account by hand, anytime. All on your own computer, with no limits.",
    ctaPrimary: "Get access →",
    ctaSecondary: "Why DrunkCtrl",
  },
  stats: [
    { big: "∞", small: "accounts & ad cabinets" },
    { big: "1 plan", small: "everything included" },
    { big: "0", small: "of your data in the cloud" },
    { big: "seconds", small: "to check an account" },
  ],
  why: {
    eyebrow: "// why DrunkCtrl",
    heading: "Stronger, cheaper and safer than a zoo of tools.",
    items: [
      { title: "No limits", body: "As many accounts, cabinets and actions as you want. One subscription — not a fee per account like antidetect browsers charge." },
      { title: "Not the cloud — your computer", body: "Accounts, passwords and cookies live only on your PC and never touch anyone else's servers." },
      { title: "Built-in antidetect browser", body: "Open any account in a full browser in one click — with its own fingerprint, proxy and cookies. Step in by hand whenever you need: pass a checkpoint, review a cabinet, tweak manually." },
      { title: "Bulk actions", body: "Check, accept policy, bind cards, launch ads — across hundreds of accounts in one click." },
      { title: "All in one", body: "Checks, antidetect browser, cards, ad launches and stats — in one window. No more juggling a dozen tools and spreadsheets." },
      { title: "Speed", body: "The status of every account in seconds — without opening a browser for each. Routine time drops several times over." },
    ],
  },
  features: {
    eyebrow: "// what it does",
    heading: "All account work — in one app.",
    items: [
      { title: "Account checks", body: "Know in seconds for each: alive / banned / under review, whether a card is attached and the ad policy accepted." },
      { title: "Built-in antidetect browser", body: "Open any account in a full browser in one click — own fingerprint, proxy and cookies. Full manual control when you need it." },
      { title: "Policy acceptance", body: "Accept the Facebook ad policy in bulk across a batch of accounts — no manual clicks." },
      { title: "Cards & limits", body: "Attach or remove cards and set spend limits across many accounts at once." },
      { title: "Access transfer", body: "Move ad cabinets and pages between your own accounts and business managers." },
      { title: "Ad launches", body: "Campaigns, creatives, audiences and budgets — across many accounts at once, from templates." },
      { title: "Statistics", body: "All campaign analytics in one window — with start, stop and budget changes right from the panel." },
      { title: "Scenarios", body: "Build a chain «check → accept policy → bind card → launch» and run it across all accounts with one button." },
    ],
  },
  pricing: {
    eyebrow: "// access",
    heading: "One subscription. Everything included.",
    sub: "Starts at $50/month. No surcharge for the number of accounts — run thousands.",
    from: "from",
    per: "/ mo",
    bullets: [
      "No limits: as many accounts and cabinets as you want",
      "Built-in antidetect browser — open any account in 1 click",
      "Checks, policy, cards, access, ads, statistics",
      "Bulk actions and automation scenarios",
      "Runs on your computer — data not in the cloud",
      "Updates and new features included",
    ],
    cta: "Get access",
    note: "now — waitlist",
  },
  waitlist: {
    eyebrow: "// request",
    heading: "Reserve your access to DrunkCtrl",
    sub1: "Leave a Telegram or email — we'll write when the subscription opens. Or ping us at ",
    tg: "@drunkctrl",
    sub2: ".",
    form: {
      contactPlaceholder: "@telegram or email",
      submit: "Join waitlist",
      submitting: "Sending…",
      volumePrompt: "How many accounts do you run? (optional)",
      volumeOptions: [
        { value: "<50", label: "under 50" },
        { value: "50-200", label: "50–200" },
        { value: "200-1000", label: "200–1000" },
        { value: "1000+", label: "1000+" },
      ],
      okTag: "// request received",
      okTitle: "You're on the waitlist 🍻",
      okSub: "We'll message you on Telegram when access opens.",
      errContact: "Enter a Telegram or email",
      errSend: "Didn't send. Message @drunkctrl directly.",
      privacy: "No spam. Only an email when access opens.",
    },
  },
  faq: {
    eyebrow: "// faq",
    heading: "FAQ",
    items: [
      { q: "Is it an app on my machine or a cloud site?", a: "It installs on your computer (Windows). All accounts, passwords and cookies are stored locally and never go to anyone else's servers." },
      { q: "Can I log into an account by hand?", a: "Yes. The built-in antidetect browser opens any account in one click — with its own fingerprint, proxy and cookies. Pass a checkpoint, review a cabinet or tweak something manually anytime automation isn't enough." },
      { q: "Is there a limit on the number of accounts?", a: "No limits. Run thousands of accounts and cabinets — the subscription price doesn't change." },
      { q: "How do payment and access work?", a: "One subscription, everything included. The waitlist is open now — leave a contact and we'll write when access opens." },
    ],
  },
  footer: {
    tagline: "FB account management",
    links: { telegram: "telegram", why: "why", access: "access" },
  },
  dash: {
    title: "DrunkCtrl — Accounts",
    countLabel: "accounts",
    checkAll: "Check all",
    summary: ["198 active", "31 policy", "11 banned"],
    status: { ok: "Active", check: "Review", ban: "Banned" },
    card: "card",
  },
};
